config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get 'session/demo', to: 'sessions#demo_account'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show]
    resources :friendships, only: [:create, :destroy]
    resources :habits, except: [:new] do
      resources :habit_days, only: [:create, :destroy]
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token

  validates :username, :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  has_many :habits, dependent: :destroy
  has_many :habit_days, through: :habits, source: :habit_days, dependent: :destroy

  has_many :created_friendships, foreign_key: :init_friend_id, class_name: "Friendship", dependent: :destroy
  has_many :recieved_friendships, foreign_key: :recp_friend_id, class_name: "Friendship", dependent: :destroy

  has_many :friends, through: :created_friendships, source: :recp_user, dependent: :destroy


  def gravatar
    gravatar_id = Digest::MD5::hexdigest(self.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end

  def currentTotal
    total_units = 0
    self.habits.each do |habit|
      total_units += habit.weight
    end
    # let's do this later
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user.nil? || !user.is_password?(password)
      return nil
    end
    return user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def is_password?(password)
      BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    unless password.nil?
      @password = password
      self.password_digest = BCrypt::Password.create(password)
    end
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show, :update]

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      signin_user!(@user)
      welcome_habit = @user.habits.create({
        title: "Welcome to HabiTrack!",
        weight: 2,
        num_days_per_week: 1
      })

      redirect_to root_url
    else
      flash.now[:danger] = @user.errors.full_messages
      render 'new'
    end
  end

  def update

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="row sign-in-row">
  <div class="col-xs-7 col-xs-offset-1 left-side-login">
  </div>
  <div class="col-xs-4" id="sign_up_form">
    <h1>Sign Up</h1>
    <form role="form" id="actual-form" action="<%= users_url %>" method="POST">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="form-group">
        <!-- <label for="username_input">Username</label> -->
        <input type="text"
               class="form-control"
               name="user[username]"
               id="username_input"
               placeholder="Username"
               value="<%= @user.username %>">
      </div>
      <div class="form-group">
        <!-- <label for="email_input">Email</label> -->
        <input type="email"
               class="form-control"
               name="user[email]"
               id="email_input"
               placeholder="Email"
               value="<%= @user.email %>">
      </div>
      <div class="form-group">
        <!-- <label for="password_input">Password</label> -->
        <input type="password"
               class="form-control"
               name="user[password]"
               id="password_input"
               placeholder="Password">
      </div>
      <button type="submit" class="pull-left btn btn-primary">Sign Up</button>

    </form>

  <div class="pull-right demo-account-button">
    <%= button_to "Log in as Guest", session_demo_url, class: 'btn btn-success btn-lg', method: :get %>
  </div>

  </div>
</div>