config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  get 'session/demo', to: 'sessions#demo_account'

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show]
    resources :friendships, only: [:create, :destroy]
    resources :habits, except: [:new] do
      resources :habit_days, only: [:create, :destroy]
    end
  end

end

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-static-top navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <img src="/assets/logoSym.png" id="logo">
          HabiTrack</a>
      </div>
      <% if signed_in? %>

      <div class="pull-right">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#" class="nav-notifications">
            <span class="glyphicon glyphicon-bell"> </span>
             <span class="">0</span></a></li>
          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu inverse-dropdown">
              <li><a href="#">Settings</a></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", session_url, method: :delete %>
              </li>
            </ul>

          </li>
        </ul>
      </div>

      <% else %>

      <form class="navbar-form navbar-right pull-right" role="login" action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group">
          <input type="text"
                 class="form-control"
                 name="username"
                 id="username_input"
                 placeholder="Username"
                 value="<%= @user.username %>">
        </div>
        <div class="form-group">
          <input type="password"
                 class="form-control"
                 name="password"
                 id="password_input"
                 placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
      </form>

      <% end %>

    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HabitrackApp</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/header" %>

    <% flash.each do |key, value| %>
    <div class="row">
      <div class="<%= "alert alert-#{key}"%>">
        <% value.each do |msg|%>
          <%= msg %>
            <br>
        <% end %>
      </div>
    </div>
    <% end %>

  <div class="container">

  <%= yield %>



</div>
</body>
</html>